// layout.jsx
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { Providers } from "@/redux/Providers";
import TranslationProvider from "@/components/layouts/TranslationProvider.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TranslationProvider>
            {children}
          </TranslationProvider>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}