import HomeHero from "@/components/home/HomeHero";
import ClientAosWrapper from "@/components/layouts/ClientAosWrapper";
import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
      <ClientAosWrapper>
        <Navbar />
        {/* <HomeHero/> */}
            {children}
        <Footer />
      </ClientAosWrapper>
  );
}